### ISSUE TITLE
referrer not set :/

### ISSUE THREAD

**Issue by Wojtek1234** [SimonMarquis/Android-InstallReferrer#3]
Any idea why on some phones google play store app does not pass referrer instead passes utm_source=(not%20set)&utm_medium=(not%20set)

many thanks !!
regards
Wojtek

**Comment by sezn** [comment]
Yeah, same thing for me, but tested on 3 devices, and no one got the refferrer.
I try to make it work on my app, and same issue with my service.

**Comment by SimonMarquis** [comment]
See #4
