### ISSUE TITLE
Issue in Timestamp

### ISSUE THREAD

**Issue by nasreekar** [SimonMarquis/Android-InstallReferrer#5]
Hi Simon,

I observed that you are setting install timestamp manually. But doesn't the API provide the timestamp by default?

I have implemented the solution but I receive both install timestamp and referral timestamp as the same. 
This is how I called the methods.
` ReferrerDetails response = referrerClient.getInstallReferrer();
            String referrer = response.getInstallReferrer();
            long referrerClickTimestampSeconds = response.getReferrerClickTimestampSeconds();
            long installBeginTimestampSeconds = response.getInstallBeginTimestampSeconds();`

and this is what I'm receiving
`"referral": {
        "uri": "utm_source=testing",
        "clickTime": "1970-01-18T23:26:26+0000",
        "installTime": "1970-01-18T23:26:26+0000"
    }`

Any idea why is this happening?

**Comment by SimonMarquis** [comment]
This implementation relies on the [Play Install Referrer Library](https://developer.android.com/google/play/installreferrer/library), therefore you might have to open a bug report on the official google bug tracker.
