### ISSUE TITLE
Web-based Google Play Store doesn't record the Install Referrer String

### ISSUE THREAD

**Issue by mitcourier** [SimonMarquis/Android-InstallReferrer#7]
Hello Simon,

I have case similar to this: https://stackoverflow.com/questions/10072467/install-referrer-is-not-tracking-on-android-web-market
If the application is installed via Google play store app, we can get the referrer properly.
But if it's installed via the web version of Google play (PC Browser, other apps' webview), we can't read the referrer.

And Google forces everyone to use their new Play Install Referrer, we can't see how to get the referrer without forcing users to Google Play (app version).
May you share some tips about this?

Thank you,
Mitch

**Comment by SimonMarquis** [comment]
Hi.
Unfortunately if the application is installed through the "remote installation" process on Google Play from another device, I don't think you'll be able to get any referrer.
On the other hand, you could try to use [Firebase Dynamic Links](https://firebase.google.com/products/dynamic-links), or even the deferred deeplinks. I wrote an extensive documentation here: https://simonmarquis.github.io/Android-App-Linking.

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by mitcourier** [comment]
Hello Simon, 

Thank you so much for your time and quick reply.
I am checking Firebase and your document now.
It seems that we may need to use many techics at the same time to get the referrer.
I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?

Sorry if i am asking too much, but from your experiences, do you see Google Analytics could help getting the source with the "remote íntallation"?

Thank you again for your time, 
Mitch

**Comment by SimonMarquis** [comment]
> I notice that in your document, Firebase doesn't support referrer. So we are getting the source of the installation from {uri: query, value: ?key=value} right?
Yes I guess so.

> do you see Google Analytics could help getting the source with the "remote íntallation"?
I won't be able to help you any further unfortunately. I'm no longer familiar enough with this whole referrer/analytics thing.

**Comment by mitcourier** [comment]
Thank you so much for your support!
