### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Abhishek9567** [SimonMarquis/Android-InstallReferrer#8]
Not working please help

**Comment by SimonMarquis** [comment]
This project uses an API deprecated by Google since march 2020.

> ⚠ Deprecated: Still Using InstallBroadcast? Switch to the Play Referrer API by March 1, 2020
> https://github.com/SimonMarquis/Android-InstallReferrer#-deprecated-still-using-installbroadcast-switch-to-the-play-referrer-api-by-march-1-2020
